-- AlterTable
ALTER TABLE "User" ADD COLUMN     "address" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "age" INTEGER NOT NULL DEFAULT 18,
ADD COLUMN     "gender" TEXT NOT NULL DEFAULT 'OTHER',
ADD COLUMN     "weight" DOUBLE PRECISION;
